server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index tour.html index.html;
        try_files $uri $uri/ /tour.html;
    }

    # Cache Control for assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|xml|svg|webp)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public";
    }
}
